name: malasraices_dart_backend
description: MalasRaices Backend - Dart + Shelf
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  postgres: ^3.4.5
  dart_jsonwebtoken: ^2.14.1
  bcrypt: ^1.1.3
  dotenv: ^4.2.0
  uuid: ^4.5.1
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.1.1
